In [1]:
# Import library
import pandas  as pd #Data manipulation
import numpy as np #Data manipulation
import matplotlib.pyplot as plt # Visualization
import seaborn as sns #Visualization

In [2]:
# Load the regression data set and take a quick look at it
regression_data = pd.read_csv("regression.csv", sep=",")
regression_data2 = pd.read_csv("regression.csv", sep=",")
regression_data2 = regression_data.values
# print(regression_data2.type())
regression_data.head()
print(regression_data2)



[[ 4.28689556  3.10367125 10.13019193]
 [ 4.00946038  3.25779376  9.67775704]
 [ 3.74583925  0.81504462  7.934881  ]
 [ 3.80402302  7.75093405 11.75636932]
 [ 4.28154031  9.60735894 13.56589509]
 [ 0.55523114  6.0425437   4.59156522]
 [ 9.77613607  7.77385868 23.64021893]
 [ 7.33839356  1.09812225 15.53827326]
 [ 4.73090165  5.05818572 12.08776382]
 [ 1.35307443  5.50762687  5.79967632]
 [ 9.33799225  7.3968391  22.61418259]
 [ 9.82541323  3.9676435  21.76464409]
 [ 9.64063213  1.18049397 20.09574413]
 [ 8.68259291  4.28521775 19.74580169]
 [ 9.31241591  8.87811806 23.29050183]
 [ 2.19966514  8.52110884  8.80110285]
 [ 8.29638405  3.62434971 18.80207089]
 [ 7.72140657  2.64442318 17.25968277]
 [ 7.75576687  4.92463229 17.99255395]
 [ 1.19525266  4.26864176  4.75635651]
 [ 1.06274464  6.7130353   5.77912429]
 [ 1.87679142  1.48738107  4.77265643]
 [ 2.63286518  3.42642821  7.21690645]
 [ 8.10956098  9.83119666 21.5784312 ]
 [ 3.87433305  5.19402709 10.62876711]
 [ 1.71584095  6.20846051

In [3]:
#check and eliminating NaN
regression_data.isnull().values.any()
#Returned false, there is no NaN

False

In [4]:
X = regression_data[["x1","x2"]]
X=X.values
# X.head()
print(type(X))
Y = regression_data[["y"]]
Y=Y.values
# Y.head()

<class 'numpy.ndarray'>


In [5]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score


# lm.intercept_


In [56]:
#check the accuracy of the offline model
from sklearn.model_selection import LeaveOneOut
cv = LeaveOneOut()
MSE_score = np.array([])
for train_i, test_i in cv.split(X):
    X_train, X_test = X[train_i], X[test_i]
    Y_train, Y_test = Y[train_i], Y[test_i]
    lm = LinearRegression()
    lm.fit(X_train,Y_train)
# lm.coef_
    y_pred = lm.predict(X_test)
    MSE_score = np.append(MSE_score, mean_squared_error(Y_test, y_pred))
avg = np.mean(MSE_score)
sd = np.std(MSE_score)
# print(avg, sd)
# print(MSE_score )

In [20]:
######Trying something for data
arr1 = [[1,2,3,4]]
arr2 = [[5,6,7,8]]
arr3 = np.concatenate((arr1, arr2))
print(arr3)
arr4 = [[]]
for i in range(4):
    arr4[0].append(i)
print(arr4)
    

[[1 2 3 4]
 [5 6 7 8]]
[[0, 1, 2, 3]]


In [62]:
#split the data for online training with 50 points, and used LOOCV
import random
cv = LeaveOneOut()

result_50 = np.array([])

MSE_overall = np.ndarray(shape = (10, 6), dtype = float)

for i in range(10):
    random.seed(i)
    # shuffle data for 10 time
#!!!!Don't delete frac = 1
### For information about frac = 1, see this website: https://stackoverflow.com/questions/29576430/shuffle-dataframe-rows
    shuffeled_data =regression_data.sample(frac=1).reset_index(drop = True)
#     shuffeled_data = shuffeled_data.values
#!!!!After shuffle, it is still a dataframe

####### for check data type
#     print(shuffeled_data.type())
#     print(shuffeled_data.shape)
######## split the pandas dataframe and put them into a list, so I am dealing with a list of dataframes
    last_check = 0
    splited_data = []
    for idx in [50,60,70,80,90,100]:
        splited_data.append(shuffeled_data.loc[last_check:idx-1])

#         print(splited_data)
        last_check=idx
#     print(splited_data[5], i)
# This is checking that I got the correct result

########Old code for shuffle, and spliting X and Y, No longer needed #################
#     shuffeled_data = np.array_split(regression_data, [50,60,70,80,90,99])
#     print(shuffeled_data.type(),shuffeled_data)
#     shuffeled_X = shuffeled_data[:,0:2]
#     shuffeled_X_split = np.array_split(shuffeled_X, [50,60,70,80,90,99])
#     shuffeled_Y = shuffeled_data[:,2:]
#     shuffeled_Y_split = np.array_split(shuffeled_Y, [50,60,70,80,90,99])
#     print(shuffeled_X_split,shuffeled_Y_split)
####################################################################################

# #     MSE_score = np.array([])
##################Old way of spliting dataset, no longer needed##################
# #     X_train, X_test, Y_train, Y_test = train_test_split(X, Y, 
# # test_size=0.5, random_state=i)
# #     X_shuffeled_train = shuffeled_data[0].values
# #     print(X_shuffeled_train.type())
####################################################################################
    



######## After got a list of dataframe (splited_data）, First train and validata the 50 with LOOCV !!

## i defined the number of the dataset, j define the round number


    for j in range(6):
#         MSE_score = np.array([])
        MSE_score = 0.0
        ##check data type and make sure they are array now
#         print(shuffeled_Y50.type())
##since the initial round used a different validation step, do a if condition
        if j == 0:
            
            shuffeled_X = splited_data[j][["x1","x2"]].values
            shuffeled_Y = splited_data[j][["y"]].values
            for train_i, test_i in cv.split(shuffeled_X):
                X_trainLO, X_testLO = shuffeled_X[train_i], shuffeled_X[test_i]
                Y_trainLO, Y_testLO = shuffeled_Y[train_i], shuffeled_Y[test_i]
                lm = LinearRegression()
                lm.fit(X_trainLO,Y_trainLO)
#         print(X_testLO.shape)
                y_pred = lm.predict(X_testLO)
#                 MSE_score = np.array([])
#         print(y_pred.shape)
                MSE_score = mean_squared_error(Y_test, y_pred)
#                 MSE_score = np.append(MSE_score, mean_squared_error(Y_test, y_pred))
#                 print(MSE_score)
#             MSE_overall_average[i,j]=np.mean(MSE_score)
#             MSE_overall_std[i,j]= np.std(MSE_score)
            
#         generate the mse for 50 data points, and store in specific array
        else:
#             print("j", j)
            additional_X = splited_data[j][["x1","x2"]].values
            additional_Y = splited_data[j][["y"]].values
#             print(additional_Y, "additional_Y")
            y_pred = lm.predict(additional_X)
#             print(y_pred, "y_pred")
#             MSE_score = np.append(MSE_score, mean_squared_error(additional_Y, y_pred))
            MSE_score = mean_squared_error(additional_Y, y_pred)
#             print(MSE_score, j)
            shuffeled_X = np.concatenate((shuffeled_X, additional_X))
            shuffeled_Y = np.concatenate((shuffeled_Y, additional_Y))
            lm.fit(shuffeled_X,shuffeled_Y)
        MSE_overall[i,j] = MSE_score
#         MSE_overall_average[i,j]=np.mean(MSE_score)
#         MSE_overall_std[i,j]= np.std(MSE_score)
      

    ######### Now, inside a for loop, do  fit (performance of the pevious model)
    # and then train the model
print(MSE_overall, MSE_overall.shape)
        
        

[[3.38618082e+00 1.50883054e-02 2.88753828e-02 1.63955389e-02
  1.80267286e-02 2.84795227e-02]
 [2.32004297e+01 3.27131225e-02 3.08595786e-02 1.93289084e-02
  2.50500719e-02 2.85366882e-02]
 [6.86190441e+00 2.65992964e-02 1.81170923e-02 1.52002050e-02
  1.92983494e-02 1.72675266e-02]
 [5.61848847e+00 9.60193796e-03 3.86335793e-02 2.70300323e-02
  1.98066285e-02 3.23276284e-02]
 [1.82517488e+02 3.28178208e-02 1.74851104e-02 2.40559268e-02
  3.29437230e-02 1.85129371e-02]
 [1.34822677e+02 2.28048580e-02 1.84621957e-02 2.00321625e-02
  1.60165602e-02 2.57236125e-02]
 [6.15795932e-02 1.51599455e-02 1.12038690e-02 2.93787755e-02
  1.95393242e-02 2.86351063e-02]
 [8.11958783e+00 2.77037590e-02 3.49857953e-02 6.11841645e-03
  2.66889392e-02 2.85395380e-02]
 [8.64783022e-02 1.06869111e-02 3.16555031e-02 1.59517971e-02
  3.15829921e-02 2.12523154e-02]
 [1.36841830e+01 2.38580494e-02 3.73183854e-02 1.26922498e-02
  1.14981212e-02 1.36104113e-02]] (10, 6)
